### GET ALL ADVANCED DATA 
GET http://localhost:3000/api/v1/advancedData/ HTTP/1.1

### GET ADVANCED DATA BY ID
GET http://localhost:3000/api/v1/advancedData/6908efcbc79ea5741a2916d2 HTTP/1.1

### POST NEW ADVANCED DATA 
POST http://localhost:3000/api/v1/advancedData/ HTTP/1.1
Content-Type: application/json

{
    "airPressure": 1013.25,
    "uvIndex": 5.7,
    "pollenIndex": 42,
    "sondaName": "brewer256@izana.aemet.es",
    "dateMedition": "2025-11-03",
    "hourMedition": "14:32:00"   
}

### PUT ADVANCED DATA BY ID    
PUT http://localhost:3000/api/v1/advancedData/6908efcbc79ea5741a2916d2 HTTP/1.1
Content-Type: application/json

{
    "airPressure": 1057.58,
    "uvIndex": 5.2,
    "pollenIndex": 51,
    "sondaName": "brewer256@izana.aemet.es",
    "dateMedition": "2025-11-02",
    "hourMedition": "17:06:00"   
}

### DELETE ADVANCED DATA BY ID
DELETE http://localhost:3000/api/v1/advancedData/6908efcbc79ea5741a2916d2 HTTP/1.1