### GET ALL PRECIPITATION DATA
GET http://localhost:3000/api/v1/precipitationData/ HTTP/1.1

### GET PRECIPITATION DATA BY ID
GET http://localhost:3000/api/v1/precipitationData/6908f9098fad9390079d11dd HTTP/1.1

### POST NEW PRECIPITATION DATA
POST http://localhost:3000/api/v1/precipitationData/ HTTP/1.1
Content-Type: application/json

    {
    "precipitationType": "Lluvia ligera",
    "precipitationProbability": 35,
    "acumulatedPrecipitation": 0.8,
    "sondaName": "pluviometro_valencia@aemet.es",
    "dateMedition": "2025-11-03",
    "hourMedition": "08:00:00"
    }

### PUT PRECIPITATION DATA BY ID    
PUT http://localhost:3000/api/v1/precipitationData/6908f9098fad9390079d11dd HTTP/1.1
Content-Type: application/json

    {
    "precipitationType": "Lluvia abundante",
    "precipitationProbability": 35,
    "acumulatedPrecipitation": 0.8,
    "sondaName": "pluviometro_valencia@aemet.es",
    "dateMedition": "2025-11-03",
    "hourMedition": "08:00:00"
    }



### DELETE PRECIPITATION DATA BY ID
DELETE http://localhost:3000/api/v1/precipitationData/6908f9098fad9390079d11dd HTTP/1.1